name: push docker image
on: [ push ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -DskipTests package
      - uses: actions/upload-artifact@master
        with:
          name: github-actions-jar
          path: target/github-actions*.jar

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test
        run: mvn test

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [ build, test ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      USER: ${{ secrets.DOCKER_USER }}
      PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        with:
          name: github-actions-jar
          path: target/github-actions*.jar
      - name: Login to Docker Hub
        run: docker login -u $USER -p $PASS
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO