name: build on macos
on: [ push ]

jobs:
  matrix-build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 9, 11, 14 ]
    name: Build with Java ${{ matrix.java }} on macos
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -DskipTests package
      - name: Test
        run: mvn test