name: github-actions
on: [push]

jobs:
  build-analyse:
    name: ubuntu_build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with Maven
        run: mvn -DskipTests package
      - name: Test
        run: mvn test

  matrix-build:
    needs: ubuntu_matrix_build_test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 9, 11, 14]
    name: Java ${{ matrix.java }} on ${{ RUNNER_OS }} build
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -DskipTests package
      - name: Test
        run: mvn test